export const ROUTES = {
  HOME: "/",
  LANDING: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  CHAT: "/dashboard",
  DOCS: "/docs",
  SECURITY: "/security",
  SECURITY_AUDIT: "/security/audit",
  POLICY: "/policy",
  RBAC: "/rbac",
  ORG: "/org",
  TEAM: "/team",
  AGENTS: "/agents",
  TASKS: "/tasks",
  MEMORY: "/memory",
  SKILLS: "/skills",
  COMMANDS: "/commands",
  PLUGINS: "/plugins",
  PRIVACY: "/privacy",
  NOTIFICATIONS: "/notifications",
  CRON: "/cron",
  USAGE: "/usage",
  SETTINGS: "/settings",
  ADD_PROVIDER: "/providers/add",
} as const;
