import { Listbox, Transition } from "@headlessui/react";
import {
  ArrowTopRightOnSquareIcon,
  CheckIcon,
  ChevronUpDownIcon,
  MagnifyingGlassIcon,
} from "@heroicons/react/24/outline";
import { Fragment, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";

import { apiClient } from "../../api/client";
import {
  CatalogueModel,
  CatalogueProvider,
  findProvider,
  OTHER_PROVIDERS,
  POPULAR_PROVIDERS,
} from "../../data/providerCatalogue";

/**
 * Setup Model page — shown when /api/me/models returns hasAny=false.
 *
 * Ported from gui/src/forms/AddModelForm.tsx so the web dashboard
 * and the IDE webview show the same provider list + model list
 * experience. Adds a personal provider via
 * PUT /api/me/providers/:slug and a personal assistant with the
 * selected model via PUT /api/me/assistants/default.
 *
 * Two paths out:
 *   1. User is allowed to add a personal provider — show the full
 *      form (provider dropdown, model dropdown, API key, base URL).
 *   2. Otherwise — show "Contact your admin" page.
 */

interface ModelsResponse {
  hasAny: boolean;
  canAddPersonal: boolean;
  hasAssistant: boolean;
}

function buildAssistantYaml(provider: CatalogueProvider, model: CatalogueModel): string {
  return [
    "# Generated by AI Firewall setup wizard.",
    "# You can edit this file any time in Settings → Assistant.",
    "name: personal",
    "schema: v1",
    "version: 0.0.1",
    "models:",
    `  - name: ${JSON.stringify(model.displayName)}`,
    `    provider: ${provider.slug}`,
    `    model: ${JSON.stringify(model.model)}`,
    "    roles:",
    ...(model.roles ?? ["chat"]).map((r) => `      - ${r}`),
    "",
  ].join("\n");
}

function ProviderListbox({
  selected,
  onSelect,
}: {
  selected: CatalogueProvider;
  onSelect: (p: CatalogueProvider) => void;
}) {
  const [query, setQuery] = useState("");

  const filter = (list: CatalogueProvider[]) =>
    query.trim().length === 0
      ? list
      : list.filter(
          (p) =>
            p.title.toLowerCase().includes(query.toLowerCase()) ||
            p.description.toLowerCase().includes(query.toLowerCase()),
        );

  return (
    <Listbox value={selected} onChange={onSelect}>
      <div className="relative">
        <Listbox.Button className="relative w-full cursor-pointer rounded-md border border-slate-700 bg-slate-800 py-2 pl-3 pr-10 text-left text-sm text-slate-100 hover:bg-slate-700/60 focus:outline-none focus:ring-2 focus:ring-emerald-500">
          <span className="block truncate font-medium">{selected.title}</span>
          <span className="block truncate text-xs text-slate-400">{selected.description}</span>
          <span className="pointer-events-none absolute inset-y-0 right-0 flex items-center pr-2">
            <ChevronUpDownIcon className="h-5 w-5 text-slate-400" />
          </span>
        </Listbox.Button>
        <Transition
          as={Fragment}
          leave="transition ease-in duration-100"
          leaveFrom="opacity-100"
          leaveTo="opacity-0"
        >
          <Listbox.Options className="absolute z-10 mt-1 max-h-80 w-full overflow-auto rounded-md border border-slate-700 bg-slate-900 py-1 text-sm shadow-lg ring-1 ring-black/20 focus:outline-none">
            <div className="sticky top-0 z-20 border-b border-slate-800 bg-slate-900 px-2 py-2">
              <div className="relative">
                <MagnifyingGlassIcon className="absolute left-2 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" />
                <input
                  type="text"
                  placeholder="Search providers…"
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  className="w-full rounded border border-slate-700 bg-slate-800 py-1 pl-7 pr-2 text-xs text-slate-100 focus:outline-none focus:ring-1 focus:ring-emerald-500"
                  onKeyDown={(e) => e.stopPropagation()}
                />
              </div>
            </div>

            {filter(POPULAR_PROVIDERS).length > 0 && (
              <div className="px-2 pt-2 pb-1 text-[10px] font-semibold uppercase tracking-wider text-slate-500">
                Popular
              </div>
            )}
            {filter(POPULAR_PROVIDERS).map((p) => (
              <Listbox.Option
                key={p.slug}
                value={p}
                className={({ active }) =>
                  `relative cursor-pointer select-none py-2 pl-10 pr-4 ${
                    active ? "bg-emerald-500/10 text-emerald-200" : "text-slate-200"
                  }`
                }
              >
                {({ selected: isSelected }) => (
                  <>
                    <div className="flex flex-col">
                      <span className="font-medium">{p.title}</span>
                      <span className="text-xs text-slate-400">{p.description}</span>
                    </div>
                    {isSelected && (
                      <span className="absolute inset-y-0 left-0 flex items-center pl-3 text-emerald-400">
                        <CheckIcon className="h-4 w-4" />
                      </span>
                    )}
                  </>
                )}
              </Listbox.Option>
            ))}

            {filter(OTHER_PROVIDERS).length > 0 && (
              <div className="px-2 pt-2 pb-1 text-[10px] font-semibold uppercase tracking-wider text-slate-500">
                Other
              </div>
            )}
            {filter(OTHER_PROVIDERS).map((p) => (
              <Listbox.Option
                key={p.slug}
                value={p}
                className={({ active }) =>
                  `relative cursor-pointer select-none py-2 pl-10 pr-4 ${
                    active ? "bg-emerald-500/10 text-emerald-200" : "text-slate-200"
                  }`
                }
              >
                {({ selected: isSelected }) => (
                  <>
                    <div className="flex flex-col">
                      <span className="font-medium">{p.title}</span>
                      <span className="text-xs text-slate-400">{p.description}</span>
                    </div>
                    {isSelected && (
                      <span className="absolute inset-y-0 left-0 flex items-center pl-3 text-emerald-400">
                        <CheckIcon className="h-4 w-4" />
                      </span>
                    )}
                  </>
                )}
              </Listbox.Option>
            ))}
          </Listbox.Options>
        </Transition>
      </div>
    </Listbox>
  );
}

function ModelListbox({
  models,
  selected,
  onSelect,
}: {
  models: CatalogueModel[];
  selected: CatalogueModel;
  onSelect: (m: CatalogueModel) => void;
}) {
  return (
    <Listbox value={selected} onChange={onSelect}>
      <div className="relative">
        <Listbox.Button className="relative w-full cursor-pointer rounded-md border border-slate-700 bg-slate-800 py-2 pl-3 pr-10 text-left text-sm text-slate-100 hover:bg-slate-700/60 focus:outline-none focus:ring-2 focus:ring-emerald-500">
          <span className="block truncate font-medium">{selected.displayName}</span>
          <span className="block truncate text-xs text-slate-400">
            {selected.description ?? selected.model}
          </span>
          <span className="pointer-events-none absolute inset-y-0 right-0 flex items-center pr-2">
            <ChevronUpDownIcon className="h-5 w-5 text-slate-400" />
          </span>
        </Listbox.Button>
        <Transition
          as={Fragment}
          leave="transition ease-in duration-100"
          leaveFrom="opacity-100"
          leaveTo="opacity-0"
        >
          <Listbox.Options className="absolute z-10 mt-1 max-h-80 w-full overflow-auto rounded-md border border-slate-700 bg-slate-900 py-1 text-sm shadow-lg ring-1 ring-black/20 focus:outline-none">
            {models.map((m) => (
              <Listbox.Option
                key={m.model}
                value={m}
                className={({ active }) =>
                  `relative cursor-pointer select-none py-2 pl-10 pr-4 ${
                    active ? "bg-emerald-500/10 text-emerald-200" : "text-slate-200"
                  }`
                }
              >
                {({ selected: isSelected }) => (
                  <>
                    <div className="flex flex-col">
                      <span className="font-medium">{m.displayName}</span>
                      <span className="font-mono text-xs text-slate-500">{m.model}</span>
                      {m.description && (
                        <span className="text-xs text-slate-400">{m.description}</span>
                      )}
                    </div>
                    {isSelected && (
                      <span className="absolute inset-y-0 left-0 flex items-center pl-3 text-emerald-400">
                        <CheckIcon className="h-4 w-4" />
                      </span>
                    )}
                  </>
                )}
              </Listbox.Option>
            ))}
          </Listbox.Options>
        </Transition>
      </div>
    </Listbox>
  );
}

export default function SetupModelPage() {
  const navigate = useNavigate();
  const [canAddPersonal, setCanAddPersonal] = useState<boolean | null>(null);
  const [provider, setProvider] = useState<CatalogueProvider>(
    findProvider("openai") ?? POPULAR_PROVIDERS[0],
  );
  const [model, setModel] = useState<CatalogueModel>(provider.models[0]);
  const [apiKey, setApiKey] = useState("");
  const [baseUrl, setBaseUrl] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // When the provider changes, reset the model selection to the
  // first entry in that provider's catalogue.
  useEffect(() => {
    setModel(provider.models[0]);
    setApiKey("");
    setBaseUrl(provider.defaultBaseUrl ?? "");
  }, [provider]);

  // Initial model-status check: if the user already has models
  // configured (race with the gate), skip straight to the dashboard.
  useEffect(() => {
    apiClient
      .get<ModelsResponse>("/api/me/models")
      .then((res) => {
        if (res.hasAny) {
          navigate("/dashboard", { replace: true });
          return;
        }
        setCanAddPersonal(res.canAddPersonal);
      })
      .catch((err) => {
        setError(
          "Could not load model status: " + (err instanceof Error ? err.message : String(err)),
        );
        setCanAddPersonal(false);
      });
  }, [navigate]);

  const apiKeyValid = useMemo(() => {
    if (!provider.requiresApiKey) return true;
    if (!apiKey.trim()) return false;
    if (!provider.keyPattern) return true;
    return provider.keyPattern.test(apiKey);
  }, [provider, apiKey]);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);

    if (provider.requiresApiKey && !apiKeyValid) {
      setError(
        `That doesn't look like a valid ${provider.title} key. Check the format and try again.`,
      );
      return;
    }
    if (provider.requiresBaseUrl && !baseUrl.trim()) {
      setError(`${provider.title} requires a base URL.`);
      return;
    }

    setSubmitting(true);
    try {
      // Step 1: save the API key. If the provider doesn't need one
      // (Ollama), send a sentinel so the server's Zod `min(1)` check
      // still passes.
      await apiClient.put(`/api/me/providers/${provider.slug}`, {
        apiKey: !provider.requiresApiKey && !apiKey ? "no-key-needed" : apiKey,
        baseUrl: baseUrl || provider.defaultBaseUrl || undefined,
      });

      // Step 2: write a personal default assistant that references
      // the picked provider + model. Without this, `/api/me/models`
      // would return hasAny=false because no assistant declares
      // the model.
      await apiClient.put("/api/me/assistants/default", {
        name: "Personal assistant",
        yaml: buildAssistantYaml(provider, model),
        isDefault: true,
      });

      // Step 3: confirm we're out of the "no models" state and
      // bounce the user into the dashboard.
      const fresh = await apiClient.get<ModelsResponse>("/api/me/models");
      if (fresh.hasAny) {
        navigate("/dashboard", { replace: true });
      } else {
        // If grants are scoped and the admin hasn't granted this
        // model yet, hasAny stays false. Tell the user the exact
        // next step.
        setError(
          "The key and assistant were saved, but your admin has not granted you access to this model yet. Ask them to grant it in Settings → Model Access.",
        );
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setSubmitting(false);
    }
  }

  // ─── Loading / gated states ────────────────────────────────

  if (canAddPersonal === null) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-slate-950 text-slate-100">
        Loading…
      </div>
    );
  }

  if (canAddPersonal === false) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-slate-950 text-slate-100">
        <div className="max-w-lg rounded-2xl border border-slate-800 bg-slate-900 p-8 text-center shadow-xl">
          <div className="text-2xl font-semibold">Model not yet configured</div>
          <p className="mt-4 text-sm text-slate-400">
            Your organization has not granted you access to any models, and your current role does
            not allow personal provider overrides.
          </p>
          <p className="mt-4 text-sm text-slate-400">
            Ask your admin to grant you a model in{" "}
            <span className="font-mono">Settings → Model Access</span>, or to relax the{" "}
            <span className="font-mono">allow_user_provider_override</span> rule in your role
            policy.
          </p>
          <button
            className="mt-6 rounded bg-slate-800 px-4 py-2 text-sm text-slate-100 hover:bg-slate-700"
            onClick={() => window.location.reload()}
          >
            Retry
          </button>
        </div>
      </div>
    );
  }

  // ─── Main form ──────────────────────────────────────────────

  return (
    <div className="flex min-h-screen items-start justify-center bg-slate-950 py-10 text-slate-100">
      <div className="w-full max-w-xl rounded-2xl border border-slate-800 bg-slate-900 p-8 shadow-xl">
        <div className="mb-2 text-center text-2xl font-semibold">Add your first model</div>
        <p className="mb-6 text-center text-sm text-slate-400">
          At least one LLM is required before you can use AI Firewall. Your key is AES-256-GCM
          encrypted in the proxy vault and never leaves your machine.
        </p>

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* ── Provider ────────────────────────────────────── */}
          <div>
            <label className="mb-1 block text-xs font-semibold text-slate-300">Provider</label>
            <ProviderListbox selected={provider} onSelect={setProvider} />
            {provider.apiKeyUrl && (
              <a
                href={provider.apiKeyUrl}
                target="_blank"
                rel="noreferrer"
                className="mt-2 inline-flex items-center gap-1 text-xs text-emerald-400 hover:text-emerald-300"
              >
                Get a {provider.title} API key
                <ArrowTopRightOnSquareIcon className="h-3 w-3" />
              </a>
            )}
          </div>

          {/* ── Model ───────────────────────────────────────── */}
          <div>
            <label className="mb-1 block text-xs font-semibold text-slate-300">Model</label>
            <ModelListbox models={provider.models} selected={model} onSelect={setModel} />
          </div>

          {/* ── API key (hidden for key-less providers) ─────── */}
          {provider.requiresApiKey && (
            <div>
              <label className="mb-1 block text-xs font-semibold text-slate-300">API key</label>
              <input
                type="password"
                value={apiKey}
                onChange={(e) => setApiKey(e.target.value)}
                placeholder={provider.keyPlaceholder ?? "Paste your API key"}
                className="w-full rounded border border-slate-700 bg-slate-800 px-3 py-2 font-mono text-sm"
                autoFocus
                required
              />
            </div>
          )}

          {/* ── Base URL (optional for most, required for Azure/Ollama/Bedrock) ── */}
          {(provider.requiresBaseUrl || provider.defaultBaseUrl) && (
            <div>
              <label className="mb-1 block text-xs font-semibold text-slate-300">
                Base URL {provider.requiresBaseUrl ? "(required)" : "(optional)"}
              </label>
              <input
                type="text"
                value={baseUrl}
                onChange={(e) => setBaseUrl(e.target.value)}
                placeholder={provider.defaultBaseUrl ?? ""}
                className="w-full rounded border border-slate-700 bg-slate-800 px-3 py-2 font-mono text-sm"
              />
            </div>
          )}

          {error && (
            <div className="rounded border border-red-900 bg-red-950/50 p-3 text-xs text-red-300">
              {error}
            </div>
          )}

          <button
            type="submit"
            disabled={submitting}
            className="w-full rounded bg-emerald-500 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-600 disabled:opacity-50"
          >
            {submitting ? "Saving…" : "Connect"}
          </button>

          <p className="text-center text-xs text-slate-500">
            This creates a personal provider key and a personal default assistant. You can edit both
            later in Settings.
          </p>
        </form>
      </div>
    </div>
  );
}
